### ISSUE TITLE
[bug] Will not connect to deemix

### ISSUE THREAD

**Issue by mon5termatt** [youegraillot/lidarr-on-steroids#16]
Log Output:

https://bin.meme.beer/?c5a5ce1130f1e1b4#2euhC5QxwNRzff9yBYwxEsx243ZxbYQGbzxa7krdUsB8

**Comment by kominoshja** [comment]
Same issue here

**Comment by youegraillot** [comment]
This should be fixes by #18

**Comment by HStep20** [comment]
Im on the latest version, but still seem to be running into this issue. Same error as the log output provided by mon5termatt

**Comment by HStep20** [comment]
Now that Im home, heres some more info:

Logs: https://pastebin.com/ZqEkzgsG

Version
    1.1.0.2629
Package Version
    pr-08ee6c8 by [hotio](https://github.com/hotio)

**Comment by youegraillot** [comment]
Ok I think I pinpointed the problem, just a matter of updating the Deemix plugin, which is not currently handled
Could you send me the content of `config\plugins\ta264\Lidarr.Plugin.Deemix` so I can add an auto-update feature ?

**Comment by HStep20** [comment]
Just the json inside, or the whole folder? Is there any PII I need to strip from it before sending as well?

**Comment by youegraillot** [comment]
The whole folder if you can please :)

**Comment by HStep20** [comment]
Link here: https://mega.nz/file/nJVlmQhQ#oCylY6i1hnV2cty7jUTROS6qm2Ee2nWZCxwGQtFW8_k

Ill remove it once you download it

**Comment by youegraillot** [comment]
I published a new image which updates the Deemix plugin on boot
Can you confirm that this is now working on your configuration ? (v1.2.4)

**Comment by HStep20** [comment]
Unfortunately, Im still getting the same error, but I think its a different issue now. The logs are showing
```
11/26/2022 11:19:52 AM
s6-supervise deemix: warning: unable to spawn ./run - waiting 10 seconds
11/26/2022 11:19:52 AM
s6-supervise setup (child): fatal: unable to exec run: Permission denied
```
So Im guessing its just not running the upgrade script. My container permission values are:

PUID: 99
PGID: 100

Which match the rest of my containers on my Unraid server

**Comment by youegraillot** [comment]
Got the same error when I tried pulling the image from dockerhub, strangely I didn't get it with locally built image

This should be fixed now with v1.2.6

**Comment by mon5termatt** [comment]
Hey y'all. Sorry for not chiming in. Been on vacation. Will test if needed when I get home

**Comment by HStep20** [comment]
Seems to be working now. Thanks!
